### PR TITLE
upgrade to node 16.16.0

### PR DESCRIPTION
**Pull request by elpoelma**
Upgrades the node version to current LTS (16.16.0).

### CODE REVIEW

**Comment by madnificent** [comment]
Discussed with @elpoelma and the upgrade of body-parser is a requirement to complete this upgrade.

**Comment by MikiDi** [comment]
Superseded by https://github.com/mu-semtech/mu-javascript-template/pull/51

**Comment by MPParsley** [comment]
@elpoelma, could you rebase this or merge master?
cf. #52

**Comment by nvdk** [comment]
I believe this can be closed in favour of #51 ?

**Comment by erikap** [comment]
Closed in favour of #51

**Pull request closed without merging**
