### PR TITLE
Expose express router

### PR DESCRIPTION
**Pull request by aatauil**

### CODE REVIEW

**Comment by madnificent** [comment]
Hi @aatauil.  Could you explain the use-case for this so we can evaluate and maybe add to the readme?  Thanks :)

**Comment by nvdk** [comment]
I assume similar to what we do here: https://github.com/lblod/notulen-prepublish-service/blob/master/app.js, we just import express.router though. see https://github.com/lblod/notulen-prepublish-service/blob/master/routes/preview.js#L11

**Comment by aatauil** [comment]
Exactly as nvdk mentioned. Yeah I tried something similar to what you linked but for some reason it did not work while developing. I probably missed something and will retry tonight :)

**Comment by aatauil** [comment]
I had to fiddle arround a bit but I indeed got it to work :) FYI goal is to have each route function in a separate file instead of one long file with all routes and half a mile worth of imports at the top. Thankss guys

**Pull request closed without merging**
